# Generated by Django 5.2.8 on 2025-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('DB', 'Database'), ('File', 'File')], max_length=10)),
                ('source_config', models.JSONField()),
                ('status', models.CharField(choices=[('pend', 'pending'), ('runn', 'running'), ('succ', 'success'), ('fail', 'failed')], max_length=10)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
