# Generated by Django 5.2.8 on 2025-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etljob',
            name='last_run',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='etljob',
            name='source_type',
            field=models.CharField(choices=[('api', 'API'), ('database', 'Database'), ('file', 'File')], max_length=10),
        ),
        migrations.AlterField(
            model_name='etljob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=10),
        ),
    ]
