# Generated by Django 5.2.8 on 2025-11-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_alter_etljob_last_run_alter_etljob_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etljob',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etljob',
            name='source_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='etljob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
