# Generated by Django 5.2.8 on 2025-11-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_etljobrun_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='etl.etljob')),
            ],
        ),
    ]
