# Generated by Django 5.2.8 on 2025-11-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_transformedrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformedrecord',
            name='job_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='etl.etljobrun'),
        ),
    ]
