# Generated by Django 5.2.8 on 2025-11-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_alter_transformedrecord_job_run'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransformedRecord',
        ),
    ]
